### ISSUE TITLE
Error when comparing merged clusters

### ISSUE THREAD

**Issue by poconnel3** [lmweber/diffcyt#19]
I am using this package to compare clusters following analysis with CATALYST package. It works fine until I subset out certain clusters post-CATALYST cluster merging. Once any clusters are removed diffcyt returns the error: "In order(as.numeric(rownames(n_cells))) : NAs introduced by coercion" and the cluster_ids do not line up with the appropriate p_values. This only occurs when "clustering_to_use" is set to search my merged clusters and not the original flowSOM clusters even though both have been removed. Any solution? I am using diffcyt V1.8.6 and CATALYST V1.12.2.
Thank you. 

My diffcyt call:
"da_res1 <- diffcyt(daf,                                            
                   formula = da_formula1, contrast = contrast,                    
                   analysis_type = "DA", method_DA = "diffcyt-DA-GLMM",           
                   clustering_to_use = "merging1", verbose = FALSE)  "

Call to subset merged clusters in CATALYST:
"daf <- filterSCE(daf, cluster_id != "Debris", k = "merging1")"

> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] diffcyt_1.8.6               CATALYST_1.12.2             SingleCellExperiment_1.10.1 SummarizedExperiment_1.18.1
 [5] DelayedArray_0.14.0         matrixStats_0.56.0          Biobase_2.48.0              GenomicRanges_1.40.0       
 [9] GenomeInfoDb_1.24.2         IRanges_2.22.2              S4Vectors_0.26.1            BiocGenerics_0.34.0        
[13] readxl_1.3.1                flowCore_2.0.1              forcats_0.5.0               stringr_1.4.0              
[17] dplyr_1.0.0                 purrr_0.3.4                 readr_1.3.1                 tidyr_1.1.0                
[21] tibble_3.0.1                ggplot2_3.3.2               tidyverse_1.3.0            

loaded via a namespace (and not attached):
  [1] backports_1.1.8             circlize_0.4.10             drc_3.0-1                   plyr_1.8.6                 
  [5] igraph_1.2.5                ConsensusClusterPlus_1.52.0 splines_4.0.1               BiocParallel_1.22.0        
  [9] scater_1.16.2               TH.data_1.0-10              digest_0.6.25               viridis_0.5.1              
 [13] fansi_0.4.1                 magrittr_1.5                CytoML_2.0.5                cluster_2.1.0              
 [17] limma_3.44.3                openxlsx_4.1.5              ComplexHeatmap_2.4.2        modelr_0.1.8               
 [21] RcppParallel_5.0.2          sandwich_2.5-1              flowWorkspace_4.0.6         cytolib_2.0.3              
 [25] jpeg_0.1-8.1                colorspace_1.4-1            blob_1.2.1                  rvest_0.3.5                
 [29] ggrepel_0.8.2               haven_2.3.1                 xfun_0.15                   crayon_1.3.4               
 [33] RCurl_1.98-1.2              jsonlite_1.7.0              hexbin_1.28.1               graph_1.66.0               
 [37] lme4_1.1-23                 survival_3.2-3              zoo_1.8-8                   glue_1.4.1                 
 [41] gtable_0.3.0                nnls_1.4                    zlibbioc_1.34.0             XVector_0.28.0             
 [45] GetoptLong_1.0.0            ggcyto_1.16.0               car_3.0-8                   BiocSingular_1.4.0         
 [49] Rgraphviz_2.32.0            shape_1.4.4                 abind_1.4-5                 scales_1.1.1               
 [53] mvtnorm_1.1-1               edgeR_3.30.3                DBI_1.1.0                   Rcpp_1.0.4.6               
 [57] plotrix_3.7-8               viridisLite_0.3.0           clue_0.3-57                 foreign_0.8-80             
 [61] rsvd_1.0.3                  FlowSOM_1.20.0              tsne_0.1-3                  httr_1.4.1                 
 [65] RColorBrewer_1.1-2          ellipsis_0.3.1              farver_2.0.3                pkgconfig_2.0.3            
 [69] XML_3.99-0.3                dbplyr_1.4.4                locfit_1.5-9.4              labeling_0.3               
 [73] tidyselect_1.1.0            rlang_0.4.6                 reshape2_1.4.4              munsell_0.5.0              
 [77] cellranger_1.1.0            tools_4.0.1                 cli_2.0.2                   generics_0.0.2             
 [81] broom_0.5.6                 ggridges_0.5.2              yaml_2.2.1                  fs_1.4.2                   
 [85] zip_2.0.4                   RBGL_1.64.0                 nlme_3.1-148                xml2_1.3.2                 
 [89] compiler_4.0.1              rstudioapi_0.11             beeswarm_0.2.3              curl_4.3                   
 [93] png_0.1-7                   reprex_0.3.0                statmod_1.4.34              stringi_1.4.6              
 [97] lattice_0.20-41             Matrix_1.2-18               nloptr_1.2.2.1              vctrs_0.3.1                
[101] pillar_1.4.4                lifecycle_0.2.0             GlobalOptions_0.1.2         BiocNeighbors_1.6.0        
[105] data.table_1.12.8           cowplot_1.0.0               bitops_1.0-6                irlba_2.3.3                
[109] R6_2.4.1                    latticeExtra_0.6-29         gridExtra_2.3               RProtoBufLib_2.0.0         
[113] rio_0.5.16                  vipor_0.4.5                 codetools_0.2-16            boot_1.3-25                
[117] MASS_7.3-51.6               gtools_3.8.2                assertthat_0.2.1            rjson_0.2.20               
[121] withr_2.2.0                 multcomp_1.4-13             GenomeInfoDbData_1.2.3      hms_0.5.3                  
[125] ncdfFlow_2.34.0             grid_4.0.1                  minqa_1.2.4                 DelayedMatrixStats_1.10.0  
[129] carData_3.0-4               Rtsne_0.15                  lubridate_1.7.9             base64enc_0.1-3            
[133] tinytex_0.24                ggbeeswarm_0.6.0

**Comment by lmweber** [comment]
Thanks for bringing this to our attention.

This was indeed a bug. When filtering with `filterSCE` removed entire clusters, the empty cluster levels ended up messing things up in some of the downstream functions (`calcCounts`, `calcMedians`, etc).

I have pushed an updated to both GitHub and Bioconductor now, which should hopefully fix this. It usually takes 1-2 days for updates to go through the Bioconductor build system. If you need it immediately, it should also work if you install from GitHub.

Let me know if there are still problems. Thanks!

**Comment by FerreiraAM-stanford** [comment]
Hi,
I have a similar issue, using the diffcyt package after a CATALYST clustering.
I used CATALYST to identify the clusters, and then filter using the filterSCE() function. This filtering step gives situation where one (or several) metacluster might not be present in the SingleCellExperiment object. While running the Differential Abundance test with the diffcyt function no error is raised however the results do not match the input, i.e. NA are not corresponding to the missing cluster(s).

I have been using diffcyt version 1.6.6 however I also tried with the current available version on github (version 1.9.7) and this does not fix the issue.
In the version 1.6.6 I identified that the line 372 in the diffcyt_wrapper() function https://github.com/lmweber/diffcyt/blob/4189cbb9186294f65fff47e85986420663aceb17/R/diffcyt_wrapper.R#L372  might be the problem. 
Replacing it by the 2 following lines of codes could potentially solve the problem (as it seems the levels/factors being used as an index is the problem):
```
  code_id_debug <- colData(d_input)$cluster_id
  code_id_debug_fixed <- as.numeric(levels(code_id_debug))[code_id_debug]
```

I am happy to provide a reproducible example if needed.
Thank you for your help.
Best regards.

**Comment by poconnel3** [comment]
Interesting that it is not working for you. The most recent update that Imweber made to the Github code in response to my initial inquiry solved the problem for me. The cluster that I filtered out is still present when diffcyt run DA analysis, but the NA's are appropriately linked to it and the rest of the P-values are assigned to the correct cluster. 
![GLMM_cluster_stats](https://user-images.githubusercontent.com/67804612/87555125-0a0f1f00-c683-11ea-8003-c9b7a97acff1.png)

**Comment by markrobinsonuzh** [comment]
@FerreiraAM-stanford perhaps we could take you up on your offer of a reproducible example, just so that @lmweber can more easily isolate the problem. Thanks! Mark

**Comment by FerreiraAM-stanford** [comment]
Hi all,
I was wondering if you were able to reproduce my example and identify the issue.

If I had this line before performing the DA test with the `diffcyt` function, the `NA` values are attributed to the right cluster (number 15):
`new_sce@colData$cluster_id <- as.numeric(as.character(new_sce@colData$cluster_id))`

Thank you for your help,
Best regards.
